### ISSUE TITLE
Crash on Dedicate servers 1.20.4

### ISSUE THREAD

**Issue by Saereth** [Swedz/MI-Tweaks#1]
Server installs Neofoge 1.20.4 are crashing on startup with an error that MI Tweaks is attempting to load client side code that is unsuitable for server distribution.

Crashlog:
https://github.com/user-attachments/files/16368868/crash-2024-07-25_00.31.54-fml.txt

Relevant bit"=
```

-- Head --
Thread: main
Stacktrace:
	at net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[loader-2.0.17.jar%2362!/:2.0] {}
-- MOD mi_tweaks --
Details:
	Caused by 0: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
		at net.swedz.mi_tweaks.MITweaksItems.<clinit>(MITweaksItems.java:38) ~[mi-tweaks-1.0.0+1.20.4.jar%23533!/:?] {re:classloading}
		at net.swedz.mi_tweaks.MITweaks.<init>(MITweaks.java:41) ~[mi-tweaks-1.0.0+1.20.4.jar%23533!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:111) ~[loader-2.0.17.jar%2362!/:2.0] {}
		at net.neoforged.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:129) ~[loader-2.0.17.jar%2362!/:2.0] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

	Mod File: /home/minecraft/mc-instances/mc-669a925dbec23/mods/mi-tweaks-1.0.0+1.20.4.jar


```

**Comment by Swedz** [comment]
Already patched in 1.0.1+1.20.4
